# Generated by Django 5.1.4 on 2025-01-20 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0002_userprofile_user_status_menupermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_asin', models.CharField(max_length=255)),
                ('customer_asin', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asin_data_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
