# Generated by Django 5.1.4 on 2025-01-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0003_asindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='asindata',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
