# Generated by Django 5.1.4 on 2025-01-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0006_taskassign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAssign',
        ),
    ]
