# Generated by Django 5.1.4 on 2025-01-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0010_alter_role_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asindata',
            old_name='customer_asin',
            new_name='candidate_asin',
        ),
        migrations.RenameField(
            model_name='taskassign',
            old_name='remark',
            new_name='region',
        ),
    ]
