# Generated by Django 5.1.4 on 2025-01-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0011_rename_customer_asin_asindata_candidate_asin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asindata',
            old_name='remark',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_assignments', to='admin_dash.asindata'),
        ),
    ]
