# Generated by Django 5.1.5 on 2025-01-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0012_rename_remark_asindata_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassign',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='q1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
