# Generated by Django 5.1.4 on 2025-01-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0013_taskassign_comment_taskassign_q1_taskassign_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='asindata',
            name='task_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_asin_data', to='admin_dash.taskassign'),
        ),
    ]
