# Generated by Django 5.1.4 on 2025-01-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0015_rename_asin_data_taskassign_asin_master_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassign',
            old_name='asin_master_id',
            new_name='asin_data',
        ),
        migrations.AddField(
            model_name='taskassign',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_assignments', to='admin_dash.asindata'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='task_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_customer_assignments', to='admin_dash.asindata'),
        ),
    ]
