# Generated by Django 5.1.5 on 2025-01-25 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0017_remove_taskassign_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='L2_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('que1', models.CharField(max_length=255, null=True)),
                ('que2', models.CharField(max_length=255, null=True)),
                ('que3', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asin_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asin_master_l2', to='admin_dash.file_upload')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l2_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
