# Generated by Django 5.1.5 on 2025-01-25 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0018_l2_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='l2_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_l2_data', to='admin_dash.l2_production'),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='l2_workstatus',
            field=models.CharField(default='Not Picked', max_length=50),
        ),
    ]
