# Generated by Django 5.1.5 on 2025-01-26 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0019_file_upload_l2_master_file_upload_l2_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='l1_workstatus',
            field=models.CharField(default='Not Picked', max_length=50),
        ),
        migrations.CreateModel(
            name='L1_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('que1', models.CharField(max_length=255, null=True)),
                ('que2', models.CharField(max_length=255, null=True)),
                ('que3', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asin_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asin_master_l1', to='admin_dash.file_upload')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l1_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file_upload',
            name='l1_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_l1_data', to='admin_dash.l1_production'),
        ),
    ]
