# Generated by Django 5.1.4 on 2025-01-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0020_file_upload_l1_workstatus_l1_production_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='picked_by',
        ),
    ]
