# Generated by Django 5.1.4 on 2025-01-27 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0021_remove_file_upload_picked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='l1_picked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l1_picked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='l2_picked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l2_picked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='l3_picked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l3_picked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
