# Generated by Django 5.1.4 on 2025-01-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0023_rename_l1_master_file_upload_l1_production_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_upload',
            old_name='l1_production',
            new_name='l1_master',
        ),
        migrations.RenameField(
            model_name='file_upload',
            old_name='l2_production',
            new_name='l2_master',
        ),
        migrations.RenameField(
            model_name='file_upload',
            old_name='l3_production',
            new_name='l3_master',
        ),
    ]
